### ISSUE TITLE
[FR] Jump back to the previous browsing position with each refresh

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#10] opened 2023-09-13 08:58 UTC
Considering that it often refreshes, is it possible to implement the functionality of returning to the last viewed position after each refresh by recording the current file name being browsed?

**Comment by TomNCatz** [comment] 2023-09-13 16:27
I would still like more information about the "it often refreshes" and what steps to reproduce the refresh are needed. 
What is refreshing? the main gallery? A block gallery?
When is it refreshing? When you resize the screen? when you're scrolling? when you change tags? when you change tabs?
Are you getting this issue on mobile or desktop?

I can look into a way to keep your scrolling place in the main gallery when there is a reload, but all of the circumstances that I know of where a reload will happen should now either be a change in which images are displayed, or where they are displayed, so keeping you in the same scroll position would not necessarily mean you are looking at the same images anyway. If you can get me more details about reproduction steps I can look into this issue more thoroughly

**Comment by TomNCatz** [comment] 2023-09-27 21:35
Closing this since I don't have enough information to reproduce the 'often refreshing' issue

**Closed by TomNCatz** 2023-09-27 21:35 UTC
Labels: bug, FR, question
