### ISSUE TITLE
[Bug]Right-clicking will add a path to the image link.

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#16] opened 2023-09-23 23:56 UTC
Right-clicking will add a path to the image link.
[[20230918195826.png]]
[[A1/20230918195826.png]]
[[A1/A1/20230918195826.png]]
[[A1/A1/A1/20230918195826.png]]

**Comment by TomNCatz** [comment] 2023-09-24 00:51
I am going to need more information than that, 
This plugin should not do anything at all with any of those links, since none of them are embeds. 
The right click functionality I have added should not change anything about the original link either, it only opens it in the side panel.
If you can check that you are still having this issue without any other plugins active and get me full reproduction steps I will look into it, but I have a suspicion something else is going on here.

**Comment by TomNCatz** [comment] 2023-09-24 02:51
I think I found what could be causing your issue, if the path to the image is wrong it tries to auto correct the path, and you seem to have found a circumstance where the path tries to correct and fails. I will remove my auto correct functionality and just fall back on an error message that tells you the path is bad and offers suggestions. This should prevent accidental link changes, but still give you the information you need to correct the issue.

**Comment by TomNCatz** [comment] 2023-09-24 04:57
Hopefully this is fixed for you in 1.1.3, please let me know if it is not and I will reopen this for investigation.

**Comment by wwjCMP** [comment] 2023-09-24 09:27
It fixes this issue. However, the problem of incorrect path has not been resolved. My path doesn't have spaces, but it contains Chinese characters, and the plugin will recognize them as spaces.

**Comment by wwjCMP** [comment] 2023-09-24 12:57
![Snipaste_2023-09-24_20-53-20](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/1ab78bd0-08a2-4db4-a4ad-417bb518889f)
![Snipaste_2023-09-24_20-52-41](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/47c3779b-ce21-42ed-846a-e422976ed69d)
It fixed this issue. However, I don't know why some image paths cannot be recognized. As shown above, I don't know what the difference in the path format of these two images is.

**Comment by TomNCatz** [comment] 2023-09-24 20:18
That looks like a locale comparison issue. I'm not really equipped for Chinese text, so if you could send me a few folder names that you know are causing issues I can try to reproduce the file structure and see if I can come up with a solution.

**Comment by wwjCMP** [comment] 2023-09-25 00:10
I have almost all the pictures stored in the root directory in the folder named "A1-附件." In fact, in the gallery, pictures from any path can be recognized normally, but they cannot be recognized when using the right-click method. Markdown files are also placed in Chinese directories.

**Comment by TomNCatz** [comment] 2023-09-25 00:21
Thank you, I will see if I can figure something out.

**Comment by wwjCMP** [comment] 2023-09-25 00:37
![Snipaste_2023-09-25_08-36-22](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/880e05ac-cf5f-4f33-a087-b270c9037906)

**Comment by TomNCatz** [comment] 2023-09-27 03:02
Has the 1.1.4 release helped with your issue, or are you still having trouble with this?

**Comment by wwjCMP** [comment] 2023-09-27 05:26
Yes, everything is running smoothly.

**Comment by wwjCMP** [comment] 2023-09-27 05:38
![Snipaste_2023-09-27_13-33-05](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/2db5f662-e32e-4bf9-9074-1d7bfbff68a2)
![Snipaste_2023-09-27_13-33-14](https://github.com/TomNCatz/obsidian-gallery/assets/32979859/20b572a3-df87-4073-9307-e2608cc11687)
However, images embedded in this format cannot be recognized. It seems like it was possible before.

**Comment by wwjCMP** [comment] 2023-09-27 05:47
I've found another issue: newly added images cannot be immediately retrieved. After right-clicking, it prompts that the resource cannot be found. After restarting Obsidian, they can be retrieved.

**Comment by FeralFlora** [comment] 2023-09-27 07:40
> I've found another issue: newly added images cannot be immediately retrieved. After right-clicking, it prompts that the resource cannot be found. After restarting Obsidian, they can be retrieved.

Maybe you should close this one and open another issue?

**Comment by TomNCatz** [comment] 2023-09-27 21:34
I've actually already found a fix for that issue and it'll go out in the next release, hopefully tonight sometime after work.

**Closed by TomNCatz** 2023-09-27 21:34 UTC
Labels: bug, question
